---
title: "Untitled"
author: "Steve, Yu"
date: "2020/5/11"
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls()); gc()
library(dplyr)
library(data.table)
library(lubridate)
library(knitr)
opts_chunk$set(echo = TRUE)
```

# 讀取資料

```{r}
chat_rawdata <- readLines("D:/My_Honey/LINE紀錄/[LINE] 與佑佑的聊天_20200506.txt", encoding = "UTF-8")
chat_rawdata %>% head
```

## 匯出的標頭

```{r}
chat_filename <- chat_rawdata[1]
chat_filenbackuptime <- chat_rawdata[2]
chat_user <- chat_rawdata %>% head(200) %>% 
  gsub("[^\\t]*\\t(.*)\\t.*", "\\1", .) %>% 
  table %>% sort(., decreasing = T) %>% 
  head(2) %>% names()

chat_tmp01 <- chat_rawdata[-c(1:3)]
```

## 資料清理01: 補齊\t

```{r}
pp1 <- paste0("([0-9]{2}\\t", chat_user[1], ")")
rr1 <- paste0("\\1\t")
pp2 <- paste0("([0-9]{2}\\t", chat_user[2], ")")
rr2 <- paste0("\\1\t")

chat_tmp01 <- chat_tmp01 %>% gsub(pp1, rr1, .)
chat_tmp01 <- chat_tmp01 %>% gsub(pp2, rr2, .)
```







```{r}
chat_tmp01 %>% head
chat_tmp01 %>% head %>% gregexpr("\\t", text = .)
```





## 資料清理05 chat_tmp02: 清理context的\t。正常只會有兩個\t，中間夾著使用者名稱。

```{r}
# chat_tmp02 <- chat_tmp01 %>% 
#   gsub(pattern = "(\\t){2,}", "\t ", .) %>% 
#   gsub(pattern = "(\\t)$", "", .) %>% 
#   gsub(pattern = "\\t5", "", .)
```

```{r}
# tmp02[87880:87890] %>% gsub(pattern = "(\\t)$", "-", .)
library(stringr)

chat_tmp02 %>% str_count(string = ., pattern = "\\t") %>% table
t1 <- chat_tmp02 %>% str_count(string = ., pattern = "\\t")
which(t1>2)
chat_tmp02[55053]
chat_tmp02[87893]


chat_tmp01[12060:12065]
tmp02[87890:87900]
tmp02[87890:87900] %>% View()
# 
tmp02[87890:87900]
tmp02[87890:87900] %>% grepl('\\"', .) %>% which()
tmp02[87890:87900][4:6]
tmp02[87890:87900][4:6] %>% paste(., collapse = "\n") %>% cat
# 


```

You unsent a message.

---

# END
